
x-common-variables: &common-variables
  RUST_LOG: "debug"
  CONFIG_FILE: "~/server-config.toml"

services:
  s1:
    image: omnipaxos-server
    build:
      context: ./..
      dockerfile: omnipaxos_server/Dockerfile
    container_name: s1
    environment:
      <<: *common-variables
    volumes:
      - ./server-1-config.toml:$HOME/server-config.toml
    ports:
      - "8001:8001"
  s2:
    image: omnipaxos-server
    container_name: s2
    environment:
      <<: *common-variables
    volumes:
      - ./server-2-config.toml:$HOME/server-config.toml
    ports:
      - "8002:8002"
  s3:
    image: omnipaxos-server
    container_name: s3
    environment:
      <<: *common-variables
    volumes:
      - ./server-3-config.toml:$HOME/server-config.toml
    ports:
      - "8003:8003"
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - postgres-network
    volumes:
      - ../pg-data/:/var/lib/god_db/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres"]

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
     - "8009:8080"
    networks:
      - postgres-network
    depends_on:
     - db

networks:
  postgres-network:
    driver: bridge
