location = "local-1"
server_id = 1
num_clients = 1 # Hardcoded number of client connections to wait for
output_filepath = "/var/log/omnipaxos/server-1.json"
# Cluster-wide settings
local_deployment = true # use localhost
cluster_name = "local-cluster"
nodes = [1, 2, 3]
initial_leader = 1
initial_flexible_quorum = { read_quorum_size = 2, write_quorum_size = 2 }
db_config = { host = "localhost", port = "5431", db = "postgres", user = "myuser", password = "mypassword" }